# Generated by Django 4.2.11 on 2024-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
