# Generated by Django 4.2.11 on 2024-04-03 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crud", "0002_alter_livro_sinopse"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendamentoExame",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("data", models.DateField(verbose_name="Data")),
                ("horario", models.TimeField(verbose_name="Horário")),
                (
                    "andamento",
                    models.CharField(
                        choices=[
                            ("Agendado", "Agendado"),
                            ("Realizado", "Realizado"),
                            ("Enviado ao laboratório", "Enviado ao laboratório"),
                            ("Concluído", "Concluído"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Agendado",
                        max_length=30,
                        verbose_name="Andamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["data", "horario"],
            },
        ),
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
                "ordering": ["nome"],
            },
        ),
        migrations.DeleteModel(
            name="Livro",
        ),
        migrations.AddField(
            model_name="agendamentoexame",
            name="exame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crud.exame",
                verbose_name="Exame",
            ),
        ),
        migrations.AddField(
            model_name="agendamentoexame",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
