# Generated by Django 4.2.11 on 2024-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0007_alter_agendamentoexame_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamentoexame",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="exame",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
