# Generated by Django 4.2.11 on 2024-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0010_alter_agendamentoexame_horario"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamentoexame",
            name="resultado",
            field=models.FileField(
                blank=True, null=True, upload_to="resultados", verbose_name="Resultados"
            ),
        ),
    ]
