# Generated by Django 4.2.11 on 2024-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0011_agendamentoexame_resultado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamentoexame",
            name="resultado",
            field=models.FileField(
                blank=True, null=True, upload_to="resultados", verbose_name="Resultado"
            ),
        ),
    ]
